using System;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Reflection;
namespace HyperTestDemo
{
[TestFixture]
public class CheckoutPage82Tests
{
    [Test]
   public void SuccessfullyPruchaseItem0()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 3);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem1()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 4);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem2()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 5);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem3()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 6);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem4()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 7);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem5()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 8);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem6()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 9);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem7()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 10);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem8()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 11);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
    [Test]
   public void SuccessfullyPruchaseItem9()
    {
        DateTime start = DateTime.Now;
       using var driver = DriverFactory.GetDriver(TestContext.CurrentContext.Test.FullName, 12);
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        var firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        var lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        var userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        var address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        var email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        var countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        var statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        var zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        var ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        var ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        var ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        var cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        var proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        driver.Navigate().GoToUrl("https://getbootstrap.com/docs/4.0/examples/checkout/");
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
        wait.Until(d => d.FindElement(By.Id("firstName")) != null);
        firstName = driver.FindElement(By.Id("firstName"));
        firstName.SendKeys("Anton");
        lastName = driver.FindElement(By.Id("lastName"));
        lastName.SendKeys("Angelov");
        userName = driver.FindElement(By.Id("username"));
        userName.SendKeys("angelovstanton");
        address = driver.FindElement(By.Id("address"));
        address.SendKeys("Flower Street 76");
        email = driver.FindElement(By.Id("email"));
        email.SendKeys("george@lambdatest.com");
        countriesSelect = new SelectElement(driver.FindElement(By.Id("country")));
        countriesSelect.SelectByText("United States");
        statesSelect = new SelectElement(driver.FindElement(By.Id("state")));
        statesSelect.SelectByText("California");
        zip = driver.FindElement(By.Id("zip"));
        zip.SendKeys("1000");
        ccname = driver.FindElement(By.Id("cc-name"));
        ccname.SendKeys("Anton Angelov");
        ccnumber = driver.FindElement(By.Id("cc-number"));
        ccnumber.SendKeys("5610591081018250");
        ccexpiration = driver.FindElement(By.Id("cc-expiration"));
        ccexpiration.SendKeys("20/10/2020");
        cccvv = driver.FindElement(By.Id("cc-cvv"));
        cccvv.SendKeys("888");
        proceedButton = driver.FindElement(By.XPath("/html/body/div/div[2]/div[2]/form/button"));
        proceedButton.Click();
        DateTime End = DateTime.Now;
        TimeSpan timeDiff = End - start;
        DriverFactory.writetocsv("ExecutionTime", timeDiff);
    }
}
}
